# Generated by Django 4.0.6 on 2022-12-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='usre_name',
            new_name='user_name',
        ),
    ]
